export const MASTERY_STAGES = [
  'Mới học 1', 'Mới học 2', 'Mới học 3',
  'Làm quen 1', 'Làm quen 2', 'Làm quen 3',
  'Nắm vững 1', 'Nắm vững 2', 'Nắm vững 3',
  'Thành thạo 1', 'Thành thạo 2', 'Thành thạo 3',
  'Tinh thông 1', 'Tinh thông 2', 'Tinh thông 3',
] as const

export const MASTERY_STAGE_COLORS = [
  'bg-rose-400', 'bg-rose-400', 'bg-rose-400',
  'bg-orange-400', 'bg-orange-400', 'bg-orange-400',
  'bg-yellow-400', 'bg-yellow-400', 'bg-yellow-400',
  'bg-lime-500', 'bg-lime-500', 'bg-lime-500',
  'bg-emerald-500', 'bg-emerald-500', 'bg-emerald-500',
] as const

export const CARD_DETAIL_COPY = {
  backLabel: 'Quay lại',
  loading: 'Đang tải...',
  notFound: 'Không tìm thấy thẻ.',
  sectionDetails: 'Chi tiết',
  sectionExamples: 'Ví dụ',
  dictLabel: 'Nghĩa từ điển',
  pitchLabel: 'Cách đọc',
  audioAriaLabel: 'Phát âm',
  addToReview: 'Thêm vào ôn tập',
  markMastered: 'Đánh dấu Tinh Thông',
  addNote: 'Thêm ghi chú',
  editNote: 'Chỉnh ghi chú',
  saveNote: 'Lưu ghi chú',
  cancelNote: 'Hủy',
  addToDeck: 'Thêm vào bộ thẻ',
  hideTranslation: 'Ẩn nghĩa',
  showTranslation: 'Hiện nghĩa',
  // Grammar
  structureLabel: 'Cấu trúc',
  toggleCasual: 'Thường',
  togglePolite: 'Lịch sự',
  registerLabel: 'Sắc thái sử dụng',
  registerInfoTitle: 'Giải thích 4 sắc thái',
  registerClose: 'Đóng',
  registers: {
    casual:   { label: 'Thân mật',   desc: 'Dùng với bạn bè, gia đình, người thân. Bỏ qua nhiều hình thức lịch sự.' },
    standard: { label: 'Tiêu chuẩn', desc: 'Trung lập, phù hợp hầu hết tình huống giao tiếp hàng ngày.' },
    polite:   { label: 'Lịch sự',    desc: 'Dùng với người lạ, đồng nghiệp, khách hàng. Hình thức ます・です.' },
    formal:   { label: 'Trang trọng',desc: 'Văn phong nghiêm túc: báo cáo, văn bản chính thức, diễn văn.' },
  },
  aboutLabel: 'Thông tin về',
  antonymsLabel: 'Trái nghĩa',
  relatedLabel: 'Cấu trúc liên quan',
  referencesLabel: 'Tham khảo',
  // Progress card
  progressTitle: 'Tiến trình học',
  nextReview: 'Ôn tập tiếp theo',
  firstLearned: 'Học lần đầu',
  reviewCount: 'Số lần đã ôn',
  reviewCountSuffix: 'lần',
  progressSettings: 'Cài đặt tiến trình',
  resetProgress: 'Đặt lại tiến trình',
  removeFromReview: 'Xóa khỏi ôn tập',
  markMasteredAction: 'Đánh dấu Tinh Thông',
  // Note editor toolbar
  noteToolBold: 'B',
  noteToolItalic: 'I',
  noteToolUnderline: 'U',
  noteToolBigger: 'A+',
  noteToolSmaller: 'A−',
  noteToolBullet: '•—',
  noteToolNumbered: '1.',
  noteToolLink: '🔗',
} as const
