export const DECK_COPY = {
  createModal: {
    titleCreate: 'Tạo bộ thẻ mới',
    titleEdit: 'Chỉnh sửa thông tin bộ thẻ',
    nameLabel: 'Tiêu đề',
    namePlaceholder: 'Nhập tên bộ thẻ...',
    nameRequired: 'Tiêu đề là bắt buộc',
    descLabel: 'Mô tả',
    descPlaceholder: 'Mô tả ngắn về bộ thẻ...',
    categoryLabel: 'Phân loại',
    coverLabel: 'Ảnh bìa',
    coverHint: 'JPG, PNG, WEBP – tối đa 5MB',
    coverBtn: 'Chọn ảnh',
    coverChange: 'Đổi ảnh',
    createBtn: 'Tạo bộ thẻ',
    saveBtn: 'Lưu thay đổi',
    cancelBtn: 'Hủy',
  },
  editPage: {
    editInfoTooltip: 'Chỉnh sửa thông tin',
    addCardBtn: 'Thêm thẻ',
    importBtn: 'Import',
    importDisabledHint: 'Tính năng đang phát triển',
    deleteBtn: 'Xóa bộ thẻ',
    searchPlaceholder: 'Tìm thẻ trong bộ...',
    creatorLabel: 'Người tạo',
    typeLabel: 'Loại',
    vocabLabel: 'Từ vựng',
    grammarLabel: 'Ngữ pháp',
    emptyList: 'Chưa có thẻ nào. Nhấn "Thêm thẻ" để bắt đầu.',
    maxCardsHint: 'Tối đa 1000 thẻ/bộ',
    confirmDeleteTitle: 'Xóa bộ thẻ?',
    confirmDeleteMsg: 'Hành động này không thể hoàn tác.',
    confirmBtn: 'Xóa',
    cancelBtn: 'Hủy',
    dragHint: 'Kéo để sắp xếp',
    removeCardAriaLabel: 'Xóa thẻ khỏi bộ',
    savedToast: 'Đã lưu thông tin bộ thẻ!',
    loading: 'Đang tải...',
    notFound: 'Không tìm thấy bộ thẻ.',
    backBtn: 'Quay lại thư viện',
  },
  addCard: {
    title: 'Thêm thẻ vào bộ',
    searchPlaceholder: 'Tìm kiếm từ vựng, ngữ pháp...',
    addBtn: 'Thêm',
    removeBtn: 'Đã thêm',
    noResults: 'Không tìm thấy thẻ phù hợp.',
    masteryLabel: 'Thành thạo',
    typeVocab: 'Từ vựng',
    typeGrammar: 'Ngữ pháp',
    doneBtn: 'Xong',
  },
  viewPage: {
    addToReviewBtn: 'Thêm vào ôn tập',
    removeFromReviewBtn: 'Xóa khỏi ôn tập',
    saveBtn: 'Lưu bộ thẻ',
    savedBtn: 'Đã lưu',
    cloneBtn: 'Sao chép',
    editBtn: 'Chỉnh sửa',
    cloneNameSuffix: '(bản sao)',
    clonedToast: 'Đã sao chép bộ thẻ!',
    savedToast: 'Đã lưu bộ thẻ!',
    perPage: 20,
    prevPage: 'Trước',
    nextPage: 'Tiếp',
    vocabLabel: 'Từ vựng',
    grammarLabel: 'Ngữ pháp',
    creatorLabel: 'Người tạo',
    totalCardsLabel: 'Tổng số thẻ',
  },
} as const

