import type { DeckStatus, DeckVisibility } from '@/types/deck'

export const DECK_COPY = {
  detailTitle: 'Chi tiết bộ thẻ',
  detailDescription: 'Xem cấu trúc bộ thẻ, từng thư mục và từng thẻ học.',
  backToLibrary: 'Quay lại thư viện',
  fork: 'Fork vào thư viện',
  bookmarked: 'Đã bookmark',
  bookmark: 'Bookmark',
  manage: 'Quản lý bộ thẻ',
  folderLabel: 'Thư mục',
  cardsLabel: 'Thẻ',
  emptyFolders: 'Bộ thẻ này chưa có thư mục nào.',
  emptyCards: 'Thư mục này chưa có thẻ nào.',
  loadFailed: 'Không thể tải chi tiết bộ thẻ.',
  createDeckTitle: 'Tạo bộ thẻ mới',
  editDeckTitle: 'Chỉnh sửa thông tin bộ thẻ',
  deckTitleLabel: 'Tiêu đề',
  deckTitlePlaceholder: 'Ví dụ: Kanji N5 cơ bản',
  deckDescriptionLabel: 'Mô tả',
  deckDescriptionPlaceholder: 'Mô tả ngắn về mục tiêu học tập của bộ thẻ này',
  deckCoverLabel: 'Ảnh bìa',
  deckCoverPlaceholder: 'Dán URL ảnh bìa nếu có',
  deckTypeLabel: 'Loại bộ thẻ',
  deckVisibilityLabel: 'Hiển thị',
  createSubmit: 'Tạo bộ thẻ',
  saveSubmit: 'Lưu thay đổi',
  cancel: 'Hủy',
  deleteDeck: 'Xóa bộ thẻ',
  confirmDeleteDeck: 'Bạn chắc chắn muốn xóa bộ thẻ này?',
  myDecksTitle: 'Bộ thẻ cá nhân',
  createFolder: 'Tạo thư mục',
  editFolder: 'Chỉnh sửa thư mục',
  deleteFolder: 'Xóa thư mục',
  addCard: 'Thêm thẻ',
  removeCard: 'Gỡ thẻ',
  saveOrder: 'Lưu thứ tự',
  moveUp: 'Đưa lên',
  moveDown: 'Đưa xuống',
  searchCardPlaceholder: 'Tìm thẻ để thêm vào thư mục',
  folderTitleLabel: 'Tên thư mục',
  folderTitlePlaceholder: 'Ví dụ: Bài 1',
  folderDescriptionLabel: 'Mô tả thư mục',
  folderDescriptionPlaceholder: 'Ghi chú ngắn cho thư mục này',
  addCardEmpty: 'Nhập từ khóa để tìm thẻ học.',
  cardSearchEmpty: 'Không tìm thấy thẻ phù hợp.',
  deckSaved: 'Đã lưu thông tin bộ thẻ.',
  deckCreated: 'Đã tạo bộ thẻ mới.',
  deckDeleted: 'Đã xóa bộ thẻ.',
  folderSaved: 'Đã lưu thư mục.',
  folderDeleted: 'Đã xóa thư mục.',
  cardAdded: 'Đã thêm thẻ vào thư mục.',
  cardRemoved: 'Đã gỡ thẻ khỏi thư mục.',
  orderSaved: 'Đã lưu thứ tự.',
  bookmarkSaved: 'Đã cập nhật bookmark.',
  forkSuccess: 'Đã fork bộ thẻ vào thư viện cá nhân.',
  duplicateCardWarning: 'Thẻ này đã tồn tại ở thư mục khác trong cùng bộ thẻ.',
  statusLabels: {
    Draft: 'Nháp',
    Published: 'Đã phát hành',
    Archived: 'Lưu trữ',
  } satisfies Record<DeckStatus, string>,
  visibilityLabels: {
    Public: 'Công khai',
    Private: 'Riêng tư',
  } satisfies Record<DeckVisibility, string>,
} as const

