import type { DeckStatus, DeckVisibility } from '@/types/deck'

export const DECK_COPY = {
  detailTitle: 'Chi tiết bộ thẻ',
  detailDescription: 'Xem cấu trúc bộ thẻ, từng thư mục và từng thẻ học.',
  backToLibrary: 'Quay lại thư viện',
  fork: 'Fork vào thư viện',
  bookmarked: 'Đã lưu',
  bookmark: 'Lưu',
  manage: 'Sửa',
  folderLabel: 'Thư mục',
  cardsLabel: 'Thẻ',
  emptyFolders: 'Bộ thẻ này chưa có thư mục nào.',
  emptyCards: 'Thư mục này chưa có thẻ nào.',
  loadFailed: 'Không thể tải chi tiết bộ thẻ.',
  createDeckTitle: 'Tạo bộ thẻ mới',
  editDeckTitle: 'Chỉnh sửa thông tin bộ thẻ',
  deckTitleLabel: 'Tiêu đề',
  deckTitlePlaceholder: 'Ví dụ: Kanji N5 cơ bản',
  deckDescriptionLabel: 'Mô tả',
  deckDescriptionPlaceholder: 'Mô tả ngắn về mục tiêu học tập của bộ thẻ này',
  deckCoverLabel: 'Ảnh bìa',
  deckCoverPlaceholder: 'Tải lên ảnh bìa cho bộ thẻ',
  deckTypeLabel: 'Loại bộ thẻ',
  deckVisibilityLabel: 'Hiển thị',
  deckTypePlaceholder: 'Chọn loại bộ thẻ',
  deckTypeEmpty: 'Chưa phân loại',
  privateVisibilityTitle: 'Riêng tư',
  privateVisibilityDescription: 'Chỉ bạn mới xem và chỉnh sửa được bộ thẻ này.',
  publicVisibilityTitle: 'Công khai',
  publicVisibilityDescription: 'Mọi người có thể xem, bookmark và fork bộ thẻ này.',
  imageUploadHint: 'PNG, JPG, WEBP hoặc GIF, tối đa 10MB.',
  createSubmit: 'Tạo bộ thẻ',
  saveSubmit: 'Lưu thay đổi',
  cancel: 'Hủy',
  deleteDeck: 'Xóa bộ thẻ',
  confirmDeleteDeck: 'Bạn chắc chắn muốn xóa bộ thẻ này?',
  myDecksTitle: 'Bộ thẻ cá nhân',
  createFolder: 'Tạo thư mục',
  editFolder: 'Chỉnh sửa thư mục',
  deleteFolder: 'Xóa thư mục',
  addCard: 'Thêm thẻ',
  importDeck: 'Import',
  importDisabledHint: 'Tính năng đang phát triển',
  removeCard: 'Gỡ thẻ',
  saveOrder: 'Lưu thứ tự',
  moveUp: 'Đưa lên',
  moveDown: 'Đưa xuống',
  editInfoTooltip: 'Chỉnh sửa thông tin bộ thẻ',
  searchDeckCardsPlaceholder: 'Lọc thẻ đang có trong bộ...',
  searchAddableCardsPlaceholder: 'Tìm thẻ để thêm vào thư mục...',
  clearSearch: 'Xóa từ khóa',
  expandFolder: 'Mở rộng thư mục',
  collapseFolder: 'Thu gọn thư mục',
  dragFolder: 'Kéo để đổi vị trí thư mục',
  dragCard: 'Kéo để đổi vị trí thẻ',
  creatorMetaLabel: 'Người tạo',
  typeMetaLabel: 'Loại',
  maxCardsHint: 'Tối đa 1000 thẻ/bộ',
  searchCardPlaceholder: 'Tìm thẻ để thêm vào thư mục',
  folderTitleLabel: 'Tên thư mục',
  folderTitlePlaceholder: 'Ví dụ: Bài 1',
  folderDescriptionLabel: 'Mô tả thư mục',
  folderDescriptionPlaceholder: 'Ghi chú ngắn cho thư mục này',
  addCardEmpty: 'Nhập từ khóa để tìm thẻ học.',
  cardSearchEmpty: 'Không tìm thấy thẻ phù hợp.',
  deckSaved: 'Đã lưu thông tin bộ thẻ.',
  deckCreated: 'Đã tạo bộ thẻ mới.',
  deckDeleted: 'Đã xóa bộ thẻ.',
  folderSaved: 'Đã lưu thư mục.',
  folderDeleted: 'Đã xóa thư mục.',
  cardAdded: 'Đã thêm thẻ vào thư mục.',
  cardRemoved: 'Đã gỡ thẻ khỏi thư mục.',
  orderSaved: 'Đã lưu thứ tự.',
  bookmarkSaved: 'Đã cập nhật bookmark.',
  forkSuccess: 'Đã fork bộ thẻ vào thư viện cá nhân.',
  duplicateCardWarning: 'Thẻ này đã tồn tại ở thư mục khác trong cùng bộ thẻ.',
  openCardAriaLabel: 'Mở chi tiết thẻ',
  removeCardAriaLabel: 'Gỡ thẻ khỏi thư mục',
  confirmDeleteDeckTitle: 'Xóa bộ thẻ?',
  confirmDeleteDeckMessage: 'Hành động này không thể hoàn tác.',
  confirmDeleteFolderTitle: 'Xóa thư mục?',
  confirmDeleteFolderMessage: 'Toàn bộ thứ tự và liên kết thẻ trong thư mục này sẽ bị xóa.',
  confirmAction: 'Xóa',
  cardTypeLabels: {
    Vocab: 'Từ vựng',
    Grammar: 'Ngữ pháp',
    Kanji: 'Kanji',
  },
  statusLabels: {
    Draft: 'Nháp',
    Published: 'Đã phát hành',
    Archived: 'Lưu trữ',
  } satisfies Record<DeckStatus, string>,
  visibilityLabels: {
    Public: 'Công khai',
    Private: 'Riêng tư',
  } satisfies Record<DeckVisibility, string>,
} as const
