export const LIBRARY_COPY = {
  pageTitle: 'Thư viện',
  pageDescription: 'Khám phá, lưu và quản lý bộ thẻ học tập của bạn trên Tacho.',
  heading: 'Thư viện',
  subheading:
    'Khám phá bộ thẻ công khai, lưu lại bộ bạn cần và quản lý thư viện cá nhân theo từng bước.',
  searchPlaceholder: 'Tìm kiếm bộ thẻ',
  createDeck: 'Tạo bộ thẻ',
  clearFilters: 'Xóa bộ lọc',
  officialOnly: 'Chỉ hiện bộ chính thức',
  allTypes: 'Tất cả loại bộ thẻ',
  allVisibilities: 'Tất cả hiển thị',
  createdByPrefix: 'Tạo bởi',
  editorLabel: 'Biên tập viên Tacho',
  reviewLabel: 'Ôn tập',
  cardCountSuffix: 'thẻ',
  mySubTabs: {
    all: 'Tất cả',
    private: 'Cá nhân',
    public: 'Công khai',
    saved: 'Đã lưu',
  },
  tabs: {
    myDecks: 'Bộ thẻ của tôi',
    systemDecks: 'Bộ thẻ Hệ thống',
    explore: 'Khám phá',
  },
  sections: {
    myDecks: 'Bộ cá nhân',
    systemDecks: 'Bộ thẻ hệ thống',
    explore: 'Bộ thẻ công khai',
  },
  states: {
    loginRequired: 'Đăng nhập để xem bookmark và thư viện cá nhân của bạn.',
    emptyExplore: 'Chưa có bộ thẻ công khai phù hợp với bộ lọc hiện tại.',
    emptyBookmarks: 'Bạn chưa lưu bộ thẻ nào.',
    emptyMyDecks: 'Bạn chưa tạo bộ thẻ nào.',
    emptySystemDecks: 'Chưa có bộ thẻ hệ thống phù hợp với bộ lọc hiện tại.',
    loadFailed: 'Không thể tải danh sách bộ thẻ.',
  },
  filters: {
    type: 'Loại bộ thẻ',
    visibility: 'Hiển thị',
  },
  actions: {
    viewDetail: 'Xem chi tiết',
    editDeck: 'Quản lý bộ thẻ',
    retry: 'Tải lại',
    nextPage: 'Trang sau',
    previousPage: 'Trang trước',
  },
  bookmarkAriaLabel: 'Đổi trạng thái bookmark',
  systemBadge: 'Tacho',
  officialBadge: 'Chính thức',
  ownerBadge: 'Của bạn',
  systemTabHint: 'Các bộ thẻ chính thức do hệ thống biên soạn.',
  exploreTabHint: 'Khám phá các bộ thẻ công khai từ cộng đồng và người dùng.',
  publicLabel: 'Công khai',
  privateLabel: 'Riêng tư',
  cardCount: (count: number) => `${count} thẻ`,
  folderCount: (count: number) => `${count} thư mục`,
  paginationSummary: (page: number, total: number) => `Trang ${page}/${Math.max(total, 1)}`,
} as const

export type LibraryTabKey = keyof typeof LIBRARY_COPY.tabs
