export const SEARCH_COPY = {
  pageTitle: 'Tìm kiếm',
  placeholder: 'Tìm kiếm từ vựng, ngữ pháp...',
  emptyQuery: 'Nhập từ khóa để bắt đầu tìm kiếm',
  vocabSection: 'Từ vựng',
  grammarSection: 'Ngữ pháp',
  emptyVocab: (q: string) => `Không tìm thấy từ vựng nào cho "${q}"`,
  emptyGrammar: (q: string) => `Không tìm thấy ngữ pháp nào cho "${q}"`,
  studyingLabel: 'Đang học',
  proLabel: 'PRO',
  markPro: 'Đánh dấu Pro',
  saveCard: 'Lưu thẻ',
  unsaveCard: 'Xóa khỏi đã lưu',
  addToDeck: 'Thêm vào bộ thẻ',
  resetProgress: 'Đặt lại tiến trình',
  addToReview: 'Thêm vào ôn tập',
  selectedCount: (n: number) => `Đã chọn ${n} thẻ`,
  bulkAddToDeck: 'Thêm vào bộ thẻ',
  bulkStartStudy: 'Bắt đầu học',
  bulkDeselect: 'Bỏ chọn',
  selectModeEnter: 'Chọn nhiều',
  selectModeExit: 'Xong',
  filterLabel: 'Bộ lọc',
  typeOptions: [
    { value: 'all', label: 'Cả hai' },
    { value: 'vocab', label: 'Từ vựng' },
    { value: 'grammar', label: 'Ngữ pháp' },
  ] as const,
  pickDeckTitle: 'Chọn bộ thẻ',
  pickDeckEmpty: 'Bạn chưa có bộ thẻ cá nhân nào.',
  pickDeckConfirm: 'Thêm',
  pickDeckCancel: 'Hủy',
} as const
